apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventdriven-demo-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/team-ohc-jp-place/eventdriven-demo.git'
    path: eventdriven-app
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: eventdriven-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true