apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/camel-k.openshift-operators: ''
  name: camel-k
  namespace: openshift-operators
spec:
  channel: stable-1.7
  installPlanApproval: Automatic
  name: camel-k
  source: community-operators
  sourceNamespace: openshift-marketplace
  #startingCSV: camel-k-operator.v1.7.0