apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: incoming-topic
  labels:
    strimzi.io/cluster: earth-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
