---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mssql-server-linux
  annotations:
    app.openshift.io/connects-to: debezium
  labels:
    app: mssql-server-linux
    app.kubernetes.io/component: mssql-server-linux
    app.kubernetes.io/instance: mssql-server-linux
    app.kubernetes.io/part-of: enterprise-app
    app.openshift.io/runtime: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-server-linux
  template:
    metadata:
      labels:
        app: mssql-server-linux
        deploymentconfig: mssql-server-linux
    spec:
      volumes:
        - name: data-sql
          configMap:
            name: data-sql
            defaultMode: 420
      containers:
        - name: mssql-server-linux
          env:
            - name: ACCEPT_EULA
              value: 'Y'
            - name: SA_PASSWORD
              value: Password!
            - name: MSSQL_PID
              value: Standard
            - name: MSSQL_AGENT_ENABLED
              value: 'true'
          image: >-
            image-registry.openshift-image-registry.svc:5000/legacy-app/mssql-docker:latest
          ports:
            - containerPort: 1433
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data-sql
              mountPath: /usr/config/configure-db.sh
              subPath: data.sql
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: mssql-server-linux
  labels:
    app: mssql-server-linux
    app.kubernetes.io/component: mssql-server-linux
    app.kubernetes.io/instance: mssql-server-linux
    app.kubernetes.io/part-of: enterprise-app
spec:
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  selector:
    app: mssql-server-linux
  type: ClusterIP
